DROP DATABASE IVP_DB;
CREATE DATABASE IVP_DB;
USE IVP_DB;
set sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE TABLE CLIENTE(
    CLIENTE_NUMERO_ID INT NOT NULL,
    CLIENTE_TIPO_ID VARCHAR(2),
    CLIENTE_TIPO VARCHAR(15) NOT NULL,
    CLIENTE_PRIMER_NOMBRE VARCHAR(50),
    CLIENTE_SEGUNDO_NOMBRE VARCHAR(50),
    CLIENTE_PRIMER_APELLIDO VARCHAR(50),
    CLIENTE_SEGUNDO_APELLIDO VARCHAR(50),
    CLIENTE_RAZON_SOCIAL VARCHAR(200),
    CLIENTE_ESTADO CHAR DEFAULT 'A',
    CLIENTE_CORREO1 VARCHAR(70) NOT NULL,
    CLIENTE_CORREO2 VARCHAR(70),
    CLIENTE_CORREO3 VARCHAR(70),
    CLIENTE_INGRESOS DOUBLE,
    CLIENTE_RUT VARCHAR(30),
    CLIENTE_FORMA_PAGO VARCHAR(20),
    CLIENTE_TELEFONO1 VARCHAR(14) NOT NULL,
    CLIENTE_TELEFONO2 VARCHAR(14),
    CLIENTE_TELEFONO3 VARCHAR(14),
    CLIENTE_CIUD_EXPED_ID VARCHAR(30),
    CLIENTE_DIGITO_VERIFICACION CHAR,    
    CLIENTE_DIRECCION_PROPI VARCHAR(100) ,
    CLIENTE_DIRECCION_COMISION VARCHAR(100),
    CLIENTE_CIUDAD_PROPIETARIO VARCHAR(30),
    CLIENTE_PERSONA_CARGO_TEL INT,
    CLIENTE_PERSONA_CARGO_OBSE VARCHAR(200),
    CLIENTE_PERSONA_CARGO VARCHAR(200),
    CLIENTE_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (CLIENTE_NUMERO_ID)
);
INSERT INTO cliente (CLIENTE_NUMERO_ID,CLIENTE_TIPO_ID,CLIENTE_TIPO,CLIENTE_PRIMER_NOMBRE,CLIENTE_SEGUNDO_NOMBRE,CLIENTE_PRIMER_APELLIDO,CLIENTE_SEGUNDO_APELLIDO,CLIENTE_CORREO1,CLIENTE_CORREO2,CLIENTE_INGRESOS,CLIENTE_RUT,CLIENTE_TELEFONO1,CLIENTE_TELEFONO2,CLIENTE_CIUD_EXPED_ID)VALUES(
                          '1014250244','CC','ARRENDATARIO','JUAN','FREDDY','RICAURTE','LOPEZ','FREDIIH@HOTMAIL.COM','FREDIIH@HOTMAIL2.COM',5000000,'101252145252',3505765962,3505765962,'BOGOTA'
);
INSERT INTO cliente (CLIENTE_NUMERO_ID,CLIENTE_TIPO_ID,CLIENTE_TIPO,CLIENTE_PRIMER_NOMBRE,CLIENTE_SEGUNDO_NOMBRE,CLIENTE_PRIMER_APELLIDO,CLIENTE_SEGUNDO_APELLIDO,CLIENTE_CORREO1,CLIENTE_CORREO2,CLIENTE_INGRESOS,CLIENTE_RUT,CLIENTE_TELEFONO1,CLIENTE_TELEFONO2,CLIENTE_CIUD_EXPED_ID)VALUES(
                          '105698782','CC','ARRENDATARIO','CAMILO','FREDDY','RICAURTE','LOPEZ','FREDIIH@HOTMAIL.COM','FREDIIH@HOTMAIL2.COM',5000000,'101252145252',3505765962,3505765962,'BOGOTA'
);
INSERT INTO cliente (CLIENTE_NUMERO_ID,CLIENTE_TIPO_ID,CLIENTE_TIPO,CLIENTE_PRIMER_NOMBRE,CLIENTE_SEGUNDO_NOMBRE,CLIENTE_PRIMER_APELLIDO,CLIENTE_SEGUNDO_APELLIDO,CLIENTE_CORREO1,CLIENTE_CORREO2,CLIENTE_INGRESOS,CLIENTE_RUT,CLIENTE_TELEFONO1,CLIENTE_TELEFONO2,CLIENTE_CIUD_EXPED_ID)VALUES(
                          '798658','CC','ARRENDATARIO','FELIPE','FREDDY','RICAURTE','LOPEZ','FREDIIH@HOTMAIL.COM','FREDIIH@HOTMAIL2.COM',5000000,'101252145252',3505765962,3505765962,'BOGOTA'
);
INSERT INTO cliente (CLIENTE_NUMERO_ID,CLIENTE_TIPO_ID,CLIENTE_TIPO,CLIENTE_PRIMER_NOMBRE,CLIENTE_SEGUNDO_NOMBRE,CLIENTE_PRIMER_APELLIDO,CLIENTE_SEGUNDO_APELLIDO,CLIENTE_CORREO1,CLIENTE_CORREO2,CLIENTE_INGRESOS,CLIENTE_RUT,CLIENTE_TELEFONO1,CLIENTE_TELEFONO2,CLIENTE_CIUD_EXPED_ID)VALUES(
                          '9876532','CC','ARRENDATARIO','ANA','MARIA','RICAURTE','LOPEZ','FREDIIH@HOTMAIL.COM','FREDIIH@HOTMAIL2.COM',5000000,'101252145252',3505765962,3505765962,'BOGOTA'
);
INSERT INTO cliente (CLIENTE_NUMERO_ID,CLIENTE_TIPO_ID,CLIENTE_TIPO,CLIENTE_PRIMER_NOMBRE,CLIENTE_SEGUNDO_NOMBRE,CLIENTE_PRIMER_APELLIDO,CLIENTE_SEGUNDO_APELLIDO,CLIENTE_CORREO1,CLIENTE_CORREO2,CLIENTE_INGRESOS,CLIENTE_RUT,CLIENTE_TELEFONO1,CLIENTE_TELEFONO2,CLIENTE_CIUD_EXPED_ID)VALUES(
                          '6546513','CC','ARRENDATARIO','ANDREA','ERIKA','RICAURTE','LOPEZ','FREDIIH@HOTMAIL.COM','FREDIIH@HOTMAIL2.COM',5000000,'101252145252',3505765962,3505765962,'BOGOTA'
);
CREATE TABLE CONTRATO(
    CONTRATO_NUMERO_ID VARCHAR(10) NOT NULL UNIQUE,
    CONTRATO_CLIENTE_ID INT(15),
	CONTRATO_TIPO_ID VARCHAR(3),
    CONTRATO_VALOR DOUBLE,
    CONTRATO_FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONTRATO_FECHA_FIN TIMESTAMP,
    CONTRATO_COODEUDOR_ID1 INT, 
    CONTRATO_COODEUDOR_ID2 INT,
    CONTRATO_COODEUDOR_ID3 INT,
    CONTRATO_COODEUDOR_ID4 INT,
    CONTRATO_ESTADO CHAR DEFAULT 'A',
    CONTRATO_DIGITAL BLOB,
    CONTRATO_FECHA_REAJUSTE TIMESTAMP NULL,
    CONTRATO_INMUEBLE_ID INT NOT NULL,
    CONTRATO_FECHA_RENOVACION TIMESTAMP NULL,
    CONTRATO_ANIO INT,
    CONTRATO_FECHA_ENTREGA TIMESTAMP NULL,
    CONTRATO_MES_ENTREGA VARCHAR(2),
	CONTRATO_FORMA_PGO_PROPI VARCHAR(20),
    CONTRATO_OBS_INQUILINO VARCHAR(200),
    CONTRATO_VALOR_BASE_PROP DOUBLE,
    CONTRATO_COMISION VARCHAR(5),
    CONTRATO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONTRATO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
	PRIMARY KEY (CONTRATO_NUMERO_ID)
    /*FOREIGN KEY (CONTRATO_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_NUMERO_ID)*/
);
INSERT INTO contrato (CONTRATO_NUMERO_ID,CONTRATO_VALOR,CONTRATO_FECHA_INICIO,CONTRATO_FECHA_FIN,CONTRATO_INMUEBLE_ID)VALUES (
102023, 1250000, '2023-03-01', '2024-02-29', '10001'
);
INSERT INTO contrato (CONTRATO_NUMERO_ID,CONTRATO_VALOR,CONTRATO_FECHA_INICIO,CONTRATO_FECHA_FIN,CONTRATO_INMUEBLE_ID)VALUES (
142023, 1250000, '2023-03-01', '2024-02-29', '10001'
);
INSERT INTO contrato (CONTRATO_NUMERO_ID,CONTRATO_VALOR,CONTRATO_FECHA_INICIO,CONTRATO_FECHA_FIN,CONTRATO_INMUEBLE_ID)VALUES (
112023, 1250000, '2023-03-01', '2024-02-29', '10001'
);
INSERT INTO contrato (CONTRATO_NUMERO_ID,CONTRATO_VALOR,CONTRATO_FECHA_INICIO,CONTRATO_FECHA_FIN,CONTRATO_INMUEBLE_ID)VALUES (
122023, 1250000, '2023-03-01', '2024-02-29', '10001'
);
INSERT INTO contrato (CONTRATO_NUMERO_ID,CONTRATO_VALOR,CONTRATO_FECHA_INICIO,CONTRATO_FECHA_FIN,CONTRATO_INMUEBLE_ID)VALUES (
132023, 1250000, '2023-03-01', '2024-02-29', '10001'
);
CREATE TABLE USUARIO_TIPO (
    USUARIO_TIPO_ID INT NOT NULL AUTO_INCREMENT,
    USUARIO_TIPO VARCHAR(15) NOT NULL,
    USUARIO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (USUARIO_TIPO_ID)
    /*CONSTRAINT UT_FK FOREIGN KEY (USUARIO_TIPO_ID) REFERENCES USUARIO(USUARIO_TIPO)*/
);
INSERT INTO USUARIO_TIPO (USUARIO_TIPO,USUARIO_USUARIO_CREACION) VALUES('INQUILINO','ADMIN');
INSERT INTO USUARIO_TIPO (USUARIO_TIPO,USUARIO_USUARIO_CREACION) VALUES('PROPIETARIO','ADMIN');
INSERT INTO USUARIO_TIPO (USUARIO_TIPO,USUARIO_USUARIO_CREACION) VALUES('ASESOR','ADMIN');
INSERT INTO USUARIO_TIPO (USUARIO_TIPO,USUARIO_USUARIO_CREACION) VALUES('ADMIN','ADMIN');
CREATE TABLE USUARIO(
    USUARIO_ID INT NOT NULL AUTO_INCREMENT,
    USUARIO_USUARIO VARCHAR(20),
    USUARIO_CLIENTE_ID INT,
    USUARIO_ESTADO CHAR NOT NULL DEFAULT "A",
    USUARIO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_TIPO INT,
    USUARIO_CLAVE VARCHAR(30) NOT NULL,
    USUARIO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (USUARIO_ID)
    /*CONSTRAINT fk_USUARIO_CLIENTE_ID FOREIGN KEY (USUARIO_Tipo) REFERENCES tipo_USUARIO(TIPO_USUARIO_ID)*/
);
INSERT INTO USUARIO (USUARIO_USUARIO,USUARIO_TIPO,USUARIO_CLAVE) VALUES ('sarce',4,'sarce');
CREATE TABLE CLIENTE_TIPO(
    CLIENTE_TIPO_ID INT NOT NULL AUTO_INCREMENT,
    CLIENTE_TIPO VARCHAR(255) NOT NULL,
    CLIENTE_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (CLIENTE_TIPO_ID)
);
INSERT INTO CLIENTE_TIPO (CLIENTE_TIPO) VALUES ('INQUILINO');
INSERT INTO CLIENTE_TIPO (CLIENTE_TIPO) VALUES ('PROPIETARIO');
CREATE TABLE PARAMETRO(
    PARAMETRO_ID INT NOT NULL AUTO_INCREMENT,
    PARAMETRO_DESCRIPCION INT,
    PARAMETRO_VALOR1 VARCHAR(20),
    PARAMETRO_VALOR2 VARCHAR(20),
    PARAMETRO_VALOR3 VARCHAR(20),
    PARAMETRO_VALOR4 VARCHAR(20),
    PARAMETRO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PARAMETRO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (PARAMETRO_ID)
);
CREATE TABLE CONJUNTO(
    CONJUNTO_ID INT NOT NULL AUTO_INCREMENT,
    CONJUNTO_NOMBRE VARCHAR(200) NOT NULL,
    CONJUNTO_NOMBRE_ADMIN VARCHAR(100),
    CONJUNTO_TELEFONO_ADMIN1 INT NOT NULL,
    CONJUNTO_TELEFONO_ADMIN2 INT,
    CONJUNTO_DIRECCION VARCHAR(100),
    CONJUNTO_CIUDAD VARCHAR(100) NOT NULL,
    CONJUNTO_CORREO1 VARCHAR(70) NOT NULL,
    CONJUNTO_CORREO2 VARCHAR(70) ,
    CONJUNTO_FORMA_PAGO VARCHAR(20) NOT NULL,
    CONJUNTO_NUMERO_CUENTA VARCHAR(30),
    CONJUNTO_VALOR_ADMIN DOUBLE NOT NULL,
    CONJUNTO_VALOR_ADMIN_DESC DOUBLE,
    CONJUNTO_VALOR_ADMIN_DESC_CON DOUBLE,
    CONJUNTO_REFERENCIA1 VARCHAR(15),
    CONJUNTO_REFERENCIA2 VARCHAR(15),
    CONJUNTO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONJUNTO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (CONJUNTO_ID)
);
CREATE TABLE CUENTA_BANCARIA(
    CUENTA_ID INT NOT NULL AUTO_INCREMENT,
    CUENTA_ID_CLIENTE INT NOT NULL,
    CUENTA_TIPO VARCHAR(15) NOT NULL,
    CUENTA_TIPO_DOCUMENTO_TITULAR VARCHAR(3) NOT NULL,
    CUENTA_NUM_DOCUMENTO_TITULAR INT NOT NULL,
    CUENTA_NUMERO VARCHAR(30) NOT NULL,
    CUENTA_BANCO VARCHAR(30) NOT NULL,
    CUENTA_TITULAR VARCHAR(120) NOT NULL,
    CUENTA_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CUENTA_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (CUENTA_ID)
    /*CONSTRAINT fk_CUENTA_ID_CLIENTE FOREIGN KEY (CUENTA_ID_CLIENTE) REFERENCES CLIENTE(CLIENTE_ID)*/
);
CREATE TABLE DETALLE_INMUEBLE(
    DETALLE_ID INT NOT NULL AUTO_INCREMENT,
    DETALLE_TIPO VARCHAR(15),
    DETALLE_INMUEBLE_ID VARCHAR(15),
    DETALLE_DESC VARCHAR(15) NOT NULL,
    DETALLE_PARQUEADERO VARCHAR(15),
    DETALLE_DEPOSITO VARCHAR(15),
    DETALLE_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETALLE_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (detalle_ID)
   /* CONSTRAINT fk_Detalle_INMUEBLE_ID FOREIGN KEY (detalle_INMUEBLE_ID) REFERENCES INMUEBLE(INMUEBLE_ID)*/
);
CREATE TABLE ASESOR(
    ASESOR_ID INT NOT NULL AUTO_INCREMENT,
    ASESOR_INMUEBLE_ID INT,
    ASESOR_ESTADO CHAR DEFAULT 'A',
    ASESOR_NOMBRE_COMPLETO VARCHAR(120) NOT NULL,
    ASESOR_CORREO VARCHAR(70) NOT NULL,
    ASESOR_CLAVE VARCHAR(30),
    ASESOR_TELEFONO INT NOT NULL,
    ASESOR_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASESOR_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (ASESOR_ID)
   /* CONSTRAINT fk_ASESOR_INMUEBLE_ID  FOREIGN KEY (ASESOR_INMUEBLE_ID ) REFERENCES INMUEBLE(INMUEBLE_ID)*/
);
CREATE TABLE COODEUDOR(
    COODEUDOR_NUMERO_ID INT NOT NULL,
    COODEUDOR_LUGAR_EXP_ID VARCHAR(30),
    COODEUDOR_NOMBRE_COMPLETO VARCHAR(120),
    COODEUDOR_CONTRATO_ID INT NOT NULL,
    COODEUDOR_INMUEBLE_ID INT NOT NULL,
    COODEUDOR_CORREO1 VARCHAR(70) NOT NULL,
    COODEUDOR_CORREO2 VARCHAR(70) NOT NULL,
    COODEUDOR_INGRESOS DOUBLE,
    COODEUDOR_TELEFONO1 INT,
    COODEUDOR_TELEFONO2 INT,
    COODEUDOR_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COODEUDOR_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (COODEUDOR_NUMERO_ID)
    /*CONSTRAINT fk_COODEUDOR_CONTRATO_ID FOREIGN KEY (COODEUDOR_CONTRATO_ID) REFERENCES CONTRATO(CONTRATO_ID)*/
    /*CONSTRAINT fk_COODEUDOR_INMUEBLE_ID FOREIGN KEY (COODEUDOR_INMUEBLE_ID) REFERENCES INMUEBLE(INMUEBLE_ID)*/
);
INSERT INTO COODEUDOR (COODEUDOR_NUMERO_ID,COODEUDOR_NOMBRE_COMPLETO,COODEUDOR_CONTRATO_ID,COODEUDOR_INMUEBLE_ID,COODEUDOR_CORREO1,COODEUDOR_CORREO2,COODEUDOR_INGRESOS,COODEUDOR_TELEFONO1,COODEUDOR_TELEFONO2,COODEUDOR_LUGAR_EXP_ID)
VALUES ('101524132','CESAR JUAN RICAURTE LOPEZ','9879879','654654','CORRECOOD1@CORREO.COM','CORRECOOD1@CORREO.COM','654654654','654654654','654654654','BOGOTA');
INSERT INTO COODEUDOR (COODEUDOR_NUMERO_ID,COODEUDOR_NOMBRE_COMPLETO,COODEUDOR_CONTRATO_ID,COODEUDOR_INMUEBLE_ID,COODEUDOR_CORREO1,COODEUDOR_CORREO2,COODEUDOR_INGRESOS,COODEUDOR_TELEFONO1,COODEUDOR_TELEFONO2,COODEUDOR_LUGAR_EXP_ID)
VALUES ('101524133','CESAR CAMILO RICAURTE LOPEZ','9879879','654654','CORRECOOD1@CORREO.COM','CORRECOOD1@CORREO.COM','654654654','654654654','654654654','BOGOTA');
INSERT INTO COODEUDOR (COODEUDOR_NUMERO_ID,COODEUDOR_NOMBRE_COMPLETO,COODEUDOR_CONTRATO_ID,COODEUDOR_INMUEBLE_ID,COODEUDOR_CORREO1,COODEUDOR_CORREO2,COODEUDOR_INGRESOS,COODEUDOR_TELEFONO1,COODEUDOR_TELEFONO2,COODEUDOR_LUGAR_EXP_ID)
VALUES ('101524134','CESAR ALEX RICAURTE LOPEZ','9879879','654654','CORRECOOD1@CORREO.COM','CORRECOOD1@CORREO.COM','654654654','654654654','654654654','BOGOTA');
INSERT INTO COODEUDOR (COODEUDOR_NUMERO_ID,COODEUDOR_NOMBRE_COMPLETO,COODEUDOR_CONTRATO_ID,COODEUDOR_INMUEBLE_ID,COODEUDOR_CORREO1,COODEUDOR_CORREO2,COODEUDOR_INGRESOS,COODEUDOR_TELEFONO1,COODEUDOR_TELEFONO2,COODEUDOR_LUGAR_EXP_ID)
VALUES ('101524135','CESAR ENRIQUE RICAURTE LOPEZ','9879879','654654','CORRECOOD1@CORREO.COM','CORRECOOD1@CORREO.COM','654654654','654654654','654654654','BOGOTA');
INSERT INTO COODEUDOR (COODEUDOR_NUMERO_ID,COODEUDOR_NOMBRE_COMPLETO,COODEUDOR_CONTRATO_ID,COODEUDOR_INMUEBLE_ID,COODEUDOR_CORREO1,COODEUDOR_CORREO2,COODEUDOR_INGRESOS,COODEUDOR_TELEFONO1,COODEUDOR_TELEFONO2,COODEUDOR_LUGAR_EXP_ID)
VALUES ('101524136','CESAR SARCE RICAURTE LOPEZ','9879879','654654','CORRECOOD1@CORREO.COM','CORRECOOD1@CORREO.COM','654654654','654654654','654654654','BOGOTA');
CREATE TABLE INMUEBLE(
 	INMUEBLE_ID INT NOT NULL,
    INMUEBLE_CLIENT_ID INT NOT NULL, 
    INMUEBLE_TIPO VARCHAR(25) NOT NULL, 
 	INMUEBLE_DIRECCION VARCHAR(100) NOT NULL,
 	INMUEBLE_LOCALIDAD VARCHAR(20) ,
 	INMUEBLE_CIUDAD VARCHAR(30) NOT NULL,
 	INMUEBLE_DEPTO VARCHAR(30),
 	INMUEBLE_ZONA VARCHAR(10),
 	INMUEBLE_TIPO_NEGOCIO VARCHAR(30) NOT NULL,
 	INMUEBLE_ESTADO_NEGOCIO VARCHAR(30),
 	INMUEBLE_ESTADO VARCHAR(15),
    INMUEBLE_CONJUNTO_ID INT, 
 	INMUEBLE_URL BLOB,
    INMUEBLE_ASESOR_ID INT,
 	INMUEBLE_MATRICULA_INM VARCHAR(40),
 	INMUEBLE_CHIP VARCHAR(40),
 	INMUEBLE_RESUMEN VARCHAR(300),
 	INMUEBLE_VALOR_NEGOCIO DOUBLE ,
 	INMUEBLE_BARRIO VARCHAR(30),
	INMUEBLE_CONTRATO_ID INT,
    INMUEBLE_COD_WASI INT,
    INMUEBLE_RESPONS_PAGO_ADMIN VARCHAR(100),
    INMUEBLE_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INMUEBLE_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
 	PRIMARY KEY (INMUEBLE_ID)
    /*CONSTRAINT fk_INMUEBLE_Client_ID FOREIGN KEY (INMUEBLE_Client_ID) REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT fk_INMUEBLE_CONJUNTO_ID  FOREIGN KEY (INMUEBLE_CONJUNTO_ID ) REFERENCES CONJUNTO(CONJUNTO_ID),
    CONSTRAINT fk_INMUEBLE_ASESOR_ID  FOREIGN KEY (INMUEBLE_ASESOR_ID ) REFERENCES ASESOR(ASESOR_ID),
    /*CONSTRAINT fk_INMUEBLE_CONTRATO_ID  FOREIGN KEY (INMUEBLE_CONTRATO_ID ) REFERENCES CONTRATO(CONTRATO_ID)*/
);
CREATE TABLE ASEGURADORA(
	ASEGURADORA_CONTRATO_ID INT NOT NULL,
    ASEGURADORA_NOMBRE VARCHAR(50) NOT NULL,
    ASEGURADORA_NUM_SOL VARCHAR(30) NOT NULL,
	ASEGURADORA_CLIENTE_ID INT NOT NULL,
    ASEGURADORA_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASEGURADORA_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (ASEGURADORA_CONTRATO_ID)
    /*CONSTRAINT fk_ASEGURADORA_CONTRATO_ID FOREIGN KEY (ASEGURADORA_CONTRATO_ID) REFERENCES CONTRATO(CONTRATO_ID),
    CONSTRAINT fk_ASEGURADORA_CLIENTE_ID FOREIGN KEY (ASEGURADORA_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)*/
);
INSERT INTO aseguradora (ASEGURADORA_CONTRATO_ID,ASEGURADORA_NOMBRE,ASEGURADORA_NUM_SOL,ASEGURADORA_CLIENTE_ID) VALUES (
'102023','SEGUROS BOLIVAR','65465','1014250243'
);
INSERT INTO aseguradora (ASEGURADORA_CONTRATO_ID,ASEGURADORA_NOMBRE,ASEGURADORA_NUM_SOL,ASEGURADORA_CLIENTE_ID) VALUES (
'112023','SEGUROS BOLIVAR','65465','1014250243'
);
INSERT INTO aseguradora (ASEGURADORA_CONTRATO_ID,ASEGURADORA_NOMBRE,ASEGURADORA_NUM_SOL,ASEGURADORA_CLIENTE_ID) VALUES (
'122023','SEGUROS BOLIVAR','65465','1014250243'
);
INSERT INTO aseguradora (ASEGURADORA_CONTRATO_ID,ASEGURADORA_NOMBRE,ASEGURADORA_NUM_SOL,ASEGURADORA_CLIENTE_ID) VALUES (
'132023','SEGUROS BOLIVAR','65465','1014250243'
);
INSERT INTO aseguradora (ASEGURADORA_CONTRATO_ID,ASEGURADORA_NOMBRE,ASEGURADORA_NUM_SOL,ASEGURADORA_CLIENTE_ID) VALUES (
'142023','SEGUROS BOLIVAR','65465','1014250243'
);
CREATE TABLE CUENTA_CONTRATO_SER_PUB(
	CUENTA_CONTRATO_ID INT NOT NULL AUTO_INCREMENT,
    CUENTA_CONTRATO_TIPO VARCHAR(30) NOT NULL,
    CUENTA_CONTRATO_NUM_CUENTA VARCHAR(30) NOT NULL,
    CUENTA_CONTRATO_REF_CUENTA VARCHAR(15),
    CUENTA_CONTRATO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CUENTA_CONTRATO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (CUENTA_CONTRATO_ID)
    /*CONSTRAINT fk_CUENTA_CONTRATO_CONTRATO_ID FOREIGN KEY (CUENTA_CONTRATO_CONTRATO_ID) REFERENCES CONTRATO(CONTRATO_ID)*/
);
CREATE TABLE ASISTENCIA(
	ASISTENCIA_ID INT NOT NULL AUTO_INCREMENT,
    ASISTENCIA_DESC VARCHAR(300),
    ASISTENCIA_INMUEBLE_ID INT NOT NULL,
    ASISTENCIA_COSTO DOUBLE NOT NULL,
    ASISTENCIA_AUTORIZADOR VARCHAR(100) NOT NULL,
    ASISTENCIA_TECNICO VARCHAR(100),
    ASISTENCIA_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASISTENCIA_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASISTENCIA_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (ASISTENCIA_ID)
    /*CONSTRAINT fk_ASISTENCIA_INMUEBLE_ID FOREIGN KEY (ASISTENCIA_INMUEBLE_ID) REFERENCES INMUEBLE(INMUEBLE_ID)*/
);
CREATE TABLE PAGO(
	PAGO_ID INT NOT NULL AUTO_INCREMENT,
    PAGO_CLIENTE_ID INT NOT NULL,
 	PAGO_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAGO_CONTRATO_ID INT NOT NULL,
	PAGO_CONCEPTO VARCHAR(50) NOT NULL,
	PAGO_MONTO DOUBLE NOT NULL,
	PAGO_NUM_COMPROBANTE VARCHAR(30) NOT NULL,
	PAGO_DIGITAL BLOB,
	PAGO_PERIODO INT NOT NULL,
    PAGO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAGO_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (PAGO_ID)
    /*CONSTRAINT fk_PAGO_CLIENTE_ID FOREIGN KEY (PAGO_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID),
    CONSTRAINT fk_PAGO_CONTRATO_ID FOREIGN KEY (PAGO_CONTRATO_ID) REFERENCES CONTRATO(CONTRATO_ID)*/
);
CREATE TABLE AFECTACION_PAGO(
	AFEC_ID INT NOT NULL AUTO_INCREMENT,
    AFEC_CONTRATO_ID INT NOT NULL,
	AFEC_VALOR_DESCUENTO DOUBLE NOT NULL,
    AFEC_VALOR_DESCRIPCION VARCHAR(300),
	AFEC_TIPO VARCHAR(15) NOT NULL,
	AFEC_AUTORIZADOR VARCHAR(80),
    AFEC_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AFEC_USUARIO_CREACION VARCHAR(15) DEFAULT 'ADMIN',
    PRIMARY KEY (afec_ID)
    /*CONSTRAINT fk_Afec_CONTRATO_ID FOREIGN KEY (afec_CONTRATO_ID) REFERENCES CONTRATO(CONTRATO_ID)*/
);
